routes:
  - route: "^openapi\\.(json)$"
    # Cache API content for a short period
    headers:
      Cache-Control: "max-age=30, public"
    # Gzip the content in s3 and serving
    gzip: false
  - route: "^.+\\.(json)$"
    # Cache API content for a short period
    headers:
      Cache-Control: "max-age=180, public"
    # Gzip the content in s3 and serving
    gzip: true
