name: api

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set up a python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install nthp_api

      - name: Download SmugMug db cache
        uses: actions/cache@v1
        with:
          path: nthp.smug.db
          key: smugmug-1
      - name: Fetch prebuilt SmugMug db if not cached
        run: wget -nc https://nthp-seed.s3.eu-west-2.amazonaws.com/nthp.smug.db

      - name: Run build job
        run: nthp build .
        env:
          SMUGMUG_API_KEY: ${{ secrets.SMUGMUG_API_KEY }}
